version: '3.8'

volumes:
  stockctlVol:

services:
  db:
    container_name: stockctl-db1
    image: stockctl-db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    build:
      context: .
      dockerfile: db/Dockerfile
    volumes:
      - stockctlVol:/var/lib/mysql

  app:
    container_name: stockctl-app1
    image: stockctl-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DBPASS=pass
    ports:
      - 80:80
    depends_on:
      - db

  adminer:
    container_name: adminer1
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db